### ISSUE TITLE
Installation on Windows failed

### ISSUE THREAD

**Issue by plfbvr** [LoicGrobol/ginger#10]
I've installed ginger this way, without cairo (I'm on Windows, python=python3) :
```
python -m pip install git+https://github.com/LoicGrobol/ginger/
```

When I try to run:
```
ginger my-conllu-file
```

I get this:

```
Traceback (most recent call last):
  File "(...)\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "(...)\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "(...)\AppData\Local\Programs\Python\Python38\Scripts\ginger.exe\__main__.py", line 4, in <module>
  File "(...)\appdata\local\programs\python\python38\lib\site-packages\ginger\main.py", line 71, in <module>
    from ginger import libtreerender
  File "(...)\local\programs\python\python38\lib\site-packages\ginger\libtreerender.py", line 402, in <module>
    context: cairo.Context,
AttributeError: 'NoneType' object has no attribute 'Context'
```

(precision : I get the same error, no matter the input file)

Any idea ?

**Comment by LoicGrobol** [comment]
Oh, yes, that's entirely my fault. While I fix this, an easy workaround would be to install with cairo support (using the `[images]` specifier)

**Comment by plfbvr** [comment]
Yes but I don't want to install cairo, I only need the ASCII output format, I'll wait ☺️

**Comment by LoicGrobol** [comment]
@plefebvre91 I have prepared a fix, can you try installing with `pip install -U git+https://github.com/LoicGrobol/ginger@fix-10` and see if that solves your issue?

**Comment by plfbvr** [comment]
Yes it works!

Thank you ☺️

**Comment by LoicGrobol** [comment]
Great, I'm merging it, then :-)
